[package]
name = "ffi_createwindow"
edition = "2021"
resolver = "2"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
dispatch = "0.2.0"
[target.'cfg(target_os = "macos")'.dependencies]
dispatch = "0.2.0"
winit = "0.30.5"
